### ISSUE TITLE
by-destruct fails on existentials containing a type given by a previous argument

### ISSUE THREAD

**Issue by dmelcer9** [wilbowma/cur#121]
For example, in this partial proof:

```
  (ntac
   (∀
    (T : Type)
    (Σ (lst : (List T)) (And (== (List T) lst (nil T)) (Not (== (List T) lst (nil T)))))
    False)
   (by-intros T ex)
   (by-destruct ex #:as [(b H)])
   ...
```

The by-destruct fails with

```
..../cur/cur-lib/cur/stdlib/sigma.rkt:25:71: #%app: type mismatch: expected (List T), given (List T)
  expression: a in: a
```

It is worth noting that when a concrete type is given, the `by-destruct` has no issues:

```
(ntac
   (∀
    (Σ (lst : (List Bool)) (And (== (List Bool) lst (nil Bool)) (Not (== (List Bool) lst (nil Bool)))))
    False)
   (by-intros ex)
   (by-destruct ex #:as [(b H)])
   ...
```

**Comment by stchang** [comment]
The problem has to do with types hidden in stx props, in combination with occasional repeated type checking by `ntac`.

To see the problem more clearly, replace `(by-intros T ex)` with `(by-intros S ex)`

In general, when the goal is `(forall X something)` and you do `(by-intro Y)`, `by-intro` has to rename `X` to `Y` in `something`. 

It doesnt search the *types* of `something` (which are in stx props) though, but this is ok because the type check was already successful, so it shouldnt need those types anymore. (If you manually construct the term with this type, it will work fine.)

So in this example, the second sigma param (the implicit lambda), its type (which references `T`) doesnt get changed by `by-intro` since it's in a stx prop.

But when `destruct` tries to determine the type of the `pair` constructor arguments, in order to add them to the ctx, it starts from the surface syntax, which will re-typecheck the type.

Specifically, the problematic part is the `(P a)` type of the second argument. The `P` is the lambda from the goal, which is still expecting a `(List T)`. But the `a` argument now has type `(List S)`.

I think the right thing to do is to get rid of the redundant type check.


Btw, here is `sigma` from `cur/stdlib/sigma`, in case it makes it easier to read my reply:

```
(data Σ0 : 2 (Π (A : (Type 0)) (P : (-> A (Type 0))) (Type 0))
      (pair0 : (Π (A : (Type 0)) (P : (-> A (Type 0))) (a : A) (b : (P a)) (Σ0 A P))))
```
