### ISSUE TITLE
Horrible Type Error Messages

### ISSUE THREAD

**Issue by maxsnew** [wilbowma/cur#26]
They just say that some term is ill-typed, they don't say what the expected or inferred type was.

**Comment by wilbowma** [comment]
Fixing this is closely tied to #1, unless I care to make Redex do awful things.

**Comment by maxsnew** [comment]
One of the worst parts is that it says ill-typed no matter what the problem is. For example if you have an unbound variable it says it's ill-typed.

**Comment by wilbowma** [comment]
Working on this in issue-26, but ran into bugs in Redex. Meanwhile, I added a macro `::` which will let you assert something has a type and will give an error if not, and display the inferred type.

**Comment by wilbowma** [comment]
If you update Redex, when you get a type error in branch issue-26. you will either:
1. get a really great error message.
2. get an extremely confusing or nonsensical error message, but with more information than "this was ill-typed"
3. get a rather unhelpful error message.

The "solution" is pretty terrible so I will likely throw it out and start over, but not any time soon.

**Comment by wilbowma** [comment]
Screw issue-26 branch. That branch sucks. And whoever said this was Redex's fault is an idiot.

In a fit of inspiration, I made the better-errors branch. It uses syntax extension and reflection to get some srsly good errors in many places. Still needs some work, but I wanted to prove wrong that guy who said who blamed this on Redex on Sep 28, 2015

**Comment by wilbowma** [comment]
I now have an active user trying to formalize something in Cur, and the single biggest problem to both using Cur "manually" and adding extensions appears to be (perhaps unsurprisingly) this issue.

In particular, without better error messages, it's not clear how to make an extenson that solves your problem, because it's not clear what the problem /is/.

This needs to move to the top of the issues stack.
